---
name: Sinamics V20 Pump Station
version: 0.0.7dev11
slug: sinamics_v20
description: Read Sinamics V20 Smart Access multi-pump status and publish to MQTT for Home Assistant.
startup: services
init: false
arch:
  - aarch64
  - amd64
options:
  log_level: info
  host: "192.168.1.1"
  port: 80
  mqtt_host: core-mosquitto
  mqtt_port: 1883
  mqtt_username: mqtt_user
  mqtt_password: mqtt_pass
  mqtt_topic: "sinamics_v20/pump_station/state"
  mqtt_cmd_topic: ""
  poll_interval: 10
  connect_timeout: 5
  read_timeout: 15
  core_batch_size: 7
  extra_batch_size: 6
  extra_params_every: 1
  param_definitions:
    - "r0032:dds_float"
    - "r0035:dds_float"
    - "r0037:dds_float"
    - "r0039:dds_float"
    - "r0754:dds_float"
    - "r0027:dds_float"
schema:
  log_level: list(debug|info|warning|error)?
  host: str
  port: int
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: password
  mqtt_topic: str
  mqtt_cmd_topic: str?
  poll_interval: float
  connect_timeout: float
  read_timeout: float
  core_batch_size: int
  extra_batch_size: int
  extra_params_every: int
  param_definitions:
    - str
